### ISSUE TITLE
c s %

### ISSUE THREAD

**Issue by mKleinCreative** [mKleinCreative/printf#4]
Write a function that produces output according to a format.

Prototype: int _printf(const char *format, ...);
Returns: the number of characters printed (excluding the null byte used to end output to strings)
write output to stdout, the standard output stream
format is a character string. The format string is composed of zero or more directives. See man 3 printf for more detail. You need to handle the following conversion specifiers:
c
s
%
You don’t have to reproduce the buffer handling of the C library printf function
You don’t have to handle the flag characters
You don’t have to handle field width
You don’t have to handle precision
You don’t have to handle the length modifiers

**Comment by bdbaraban** [comment]
Wrote files `print_c.c`, `print_s.c`, and updated `_printf.c` to account for %
